[package]
name = "radicle-node"
license = "MIT OR Apache-2.0"
version = "0.2.0"
authors = ["Alexis Sellier <alexis@radicle.xyz>"]
edition = "2021"

[dependencies]
anyhow = { version = "1" }
byteorder = { version = "1" }
bloomy = { version = "1.2" }
chrono = { version = "0.4.0" }
colored = { version = "1.9.0" }
crossbeam-channel = { version = "0.5.6" }
fastrand = { version = "1.8.0" }
log = { version = "0.4.17", features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
nonempty = { version = "0.8.0", features = ["serialize"] }
nakamoto-net = { version = "0.3.0" }
nakamoto-net-poll = { version = "0.3.0" }
tempfile = { version = "3.3.0" }
thiserror = { version = "1" }

[dependencies.radicle]
path = "../radicle"
version = "0.2.0"

[dev-dependencies]
radicle = { path = "../radicle", version = "*", features = ["test"] }
quickcheck = { version = "1", default-features = false }
quickcheck_macros = { version = "1", default-features = false }
