[workspace]
members = [
  "radicle",
  "radicle-cob",
  "radicle-cli",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-dag",
  "radicle-httpd",
  "radicle-node",
  "radicle-remote-helper",
  "radicle-ssh",
  "radicle-tools",
]
default-members = [
  "radicle",
  "radicle-cli",
  "radicle-cob",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-node",
  "radicle-ssh",
  "radicle-remote-helper",
]

[profile.container]
inherits = "release"
debug = true
incremental = false

[patch.crates-io.nakamoto-net]
git = "https://github.com/cloudhead/nakamoto"
rev = "90cc3eac67aa5cfd5f42cf7cb1e2b155af3214fb"
version = "0.3.0"

[patch.crates-io.cyphernet]
git = "https://github.com/cyphernet-wg/rust-cyphernet"
rev = "7ff92b1540d25658d4810d9ca274507685af0ba6"
version = "0.1.0"

[patch.crates-io.io-reactor]
git = "https://github.com/cyphernet-wg/rust-netservices"
rev = "e48011b10db9f9575af3ff1343e077ba9175028d"
version = "0.1.0"

[patch.crates-io.netservices]
git = "https://github.com/cyphernet-wg/rust-netservices"
rev = "e48011b10db9f9575af3ff1343e077ba9175028d"
version = "0.1.0"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-git"
rev = "79a94721366490053e2d8ac1c1afa14fb0c25f09"

[patch.crates-io.git-ref-format]
git = "https://github.com/radicle-dev/radicle-git"
rev = "79a94721366490053e2d8ac1c1afa14fb0c25f09"
