[workspace]
members = [
  "radicle",
  "radicle-cob",
  "radicle-cli",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-dag",
  "radicle-httpd",
  "radicle-node",
  "radicle-remote-helper",
  "radicle-ssh",
  "radicle-tools",
]
default-members = [
  "radicle",
  "radicle-cli",
  "radicle-cob",
  "radicle-crdt",
  "radicle-crypto",
  "radicle-node",
  "radicle-ssh",
  "radicle-remote-helper",
]

[profile.container]
inherits = "release"
debug = true
incremental = false

[patch.crates-io.io-reactor]
git = "https://github.com/rust-amplify/io-reactor"
rev = "9a2e787621c78987c866b13ff820bafce248ddc5"
version = "0.1.0"

[patch.crates-io.netservices]
git = "https://github.com/cyphernet-dao/rust-netservices"
version = "0.1.0"

[patch.crates-io.radicle-git-ext]
git = "https://github.com/radicle-dev/radicle-git"
rev = "016ece66474edf45d2d304141515152e6f7b37a3"

[patch.crates-io.git-ref-format]
git = "https://github.com/radicle-dev/radicle-git"
rev = "016ece66474edf45d2d304141515152e6f7b37a3"
