[package]
name = "radicle-httpd"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Alexis Sellier <alexis@radicle.xyz>"]
edition = "2021"
default-run = "radicle-httpd"
build = "../build.rs"

[features]
default = []
logfmt = [
  "tracing-logfmt",
  "tracing-subscriber/env-filter"
]

[dependencies]
anyhow = { version = "1" }
flate2 = { version = "1" }
lexopt = { version = "0.2.1" }
thiserror = { version = "1" }
tokio = { version = "1.21", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.37", default-features = false, features = ["std", "log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "ansi", "fmt"] }
tracing-logfmt = { version = "0.2", optional = true }
axum = { version = "0.5.16", default-features = false }
axum-server = { version = "0.4.2", default-features = false }
hyper = { version = "0.14.17", default-features = false }
tower-http = { version = "0.3.4", default-features = false, features = ["trace"] }

[dependencies.radicle]
path = "../radicle"
version = "0.2.0"
